In [1]:
import torch
from d2l import torch as d2l
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda'),torch.cuda.device('cuda:1')

(device(type='cpu'),
 <torch.cuda.device at 0x2079a44ca00>)

In [2]:
torch.cuda.device_count()

1

In [4]:
def try_gpu(i=0):  #@save
    """如果存在，则返回gpu(i)，否则返回cpu()。"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  #@save
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]。"""
    devices = [torch.device(f'cuda:{i}')
             for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [5]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [6]:
X=torch.ones(size=(2,3), device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [11]:
Y = torch.rand(size= (2,3), device =try_gpu(0))
Y

tensor([[0.8733, 0.0463, 0.2831],
        [0.2496, 0.1151, 0.7435]], device='cuda:0')

In [12]:
X+Y

tensor([[1.8733, 1.0463, 1.2831],
        [1.2496, 1.1151, 1.7435]], device='cuda:0')

In [15]:
X.cuda(0) is X

True

In [16]:
net = nn.Sequential(nn.Linear(3,1))
net = net.to(device=try_gpu())

In [17]:
net(X)

tensor([[1.5547],
        [1.5547]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [18]:
net[0].weight.data.device

device(type='cuda', index=0)